on:
  push:
    branches:
      - master
name: São Lucas Telemedicina - Homologação
jobs:
  web-deploy:
    name: 🎉 Deploy Homologação - Sao Lucas Telemedicina
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: saolucas.somosdevteam.com/
